CREATE TABLE demo (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

INSERT INTO demo (name, description) VALUES
    ('first',  'Seed row created by Flyway migration V1'),
    ('second', 'Another seed row');
